version: '3.8'

services:
  frontend:
    container_name: frontend 
    hostname: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8081:80
    image: docker.io/vutrongquang/frontend