# auto detects a good number of processes to run
# worker_processes auto;

events {
#    worker_connections 8000;
    # Tells the worker to accept multiple connections at a time
#    multi_accept on;
}

http {
    # Add MIME types for CSS and JS files
    include       mime.types;
    default_type  application/octet-stream;
    

    # server {
    #     listen 80;
    #     server_name toolsdeploy.datn.live;

    #     # Redirect HTTP to HTTPS
    #     location / {
    #         return 301 https://$server_name$request_uri;
    #     }
    # }

    server {
        # listen 443 ssl;
    listen 80;
    #     server_name toolsdeploy.datn.live;

    #     ssl_certificate /etc/ssl/certs/toolsdeploy.crt;
    #     ssl_certificate_key /etc/ssl/private/toolsdeploy.key;

	# ssl_protocols TLSv1.2 TLSv1.3;
    # ssl_ciphers HIGH:!aNULL:!MD5;
    #     root   /usr/share/nginx/html;
    #     index  index.html index.htm;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html =404;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }

        # Media: images, icons, video, audio, HTC
#        location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
#          expires 1M;
#          access_log off;
#          add_header Cache-Control "public";
#        }

#        # Javascript and CSS files
#        location ~* \.(?:css|js)$ {
#            try_files $uri =404;
#            expires 1y;
#            access_log off;
#            add_header Cache-Control "public";
#        }

        # Any route containing a file extension (e.g. /devicesfile.js)
#        location ~ ^.+\..+$ {
#            try_files $uri =404;
#        }

        # Serve static files
    location /static/ {
            alias /usr/share/nginx/html/static/;
            expires max;
            add_header Cache-Control public;
    }

#	location ~ \.css {
#		add_header  Content-Type    text/css;
#	}
#	location ~ \.js {
#		add_header  Content-Type    application/x-javascript;
#	}
   }
}
